# docker-compose.yml
version: '2'

services :

    planner : 
        build : ./planner
        ports: 
            - "8080:8080"
        depends_on:
            - worker
            - worker2
            - worker3
            - worker4

    worker2 : 
        environment: 
            - PORT=3001
          #  - MULT=true
        build : ./worker
        image : worker2
        ports: 
            - "3001:3001"
        container_name: worker2
        extra_hosts:
            - host.docker.internal:host-gateway

    worker4 : 
        environment: 
            - PORT=3004
        build : ./worker
        image : worker4
        ports: 
            - "3004:3004"
        container_name: worker4
        extra_hosts:
            - host.docker.internal:host-gateway
    
    worker3 : 
        environment: 
            - PORT=3003
        build : ./worker
        image : worker3
        ports: 
            - "3003:3003"
        container_name: worker3
        extra_hosts:
            - host.docker.internal:host-gateway

    worker : 
        environment: 
            - PORT=3000
           # - ADD=true
        build : ./worker
        image : worker
        ports: 
            - "3000:3000"
        container_name: worker
        extra_hosts:
            - host.docker.internal:host-gateway